<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Avatars\" />
    <Folder Include="wwwroot\images\Máy cũ giá rẻ\" />
    <Folder Include="wwwroot\images\Màn hình máy tính\" />
    <Folder Include="wwwroot\images\PC văn phòng\" />
    <Folder Include="wwwroot\images\PC giá rẻ\" />
    <Folder Include="wwwroot\images\Phụ kiện\Chuột\" />
    <Folder Include="wwwroot\images\Phụ kiện\Bàn phím\" />
    <Folder Include="wwwroot\images\Phụ kiện\USB\" />
    <Folder Include="wwwroot\images\Phụ kiện\Tai nghe\" />
  </ItemGroup>

</Project>
